version: '3.8'

services:
  web:
    build: .
    container_name: card_inventory_app
    restart: unless-stopped
    volumes:
      - ./instance:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=0
      - SECRET_KEY=super_secret_key_for_session_security
      # Note: ADMIN_PASSWORD is no longer needed as we use database users now
      - SMTP_HOST=mail.smtp2go.com
      - SMTP_PORT=2525
      - SMTP_USER=replace_with_smtp2go_username
      - SMTP_PASS=replace_with_smtp2go_password
      - FROM_EMAIL=sales@fludmedia.com
      - ADMIN_EMAIL=replace_with_your_personal_email@gmail.com

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: card_inventory_tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - web
